### ISSUE TITLE
Thanks for sharing this plugin, how does it work and what's further roadmap?

### ISSUE THREAD

**Issue by jiangcaiyang** [1xinghuan/usdNodeGraph#3]
Building a node editor based on UsdView seems fascinating, but as USD is used by a small group of people, some studio needs to learn and further develp a lot to support it in production. I wonder how does it used in your dataflow or procedure?

**Comment by 1xinghuan** [comment]
@jiangcaiyang 
My current goal is to use this tool as a usd editing tool, because usdview itself does not support a lot of editing functions, and it is not very convenient to edit usd files in Maya (hope that it will be greatly changed in the future 2021 version). So now I will use this to do simple editing in usdview and maya, such as layout, reference, etc.
